### ISSUE TITLE
Add stop sounds button

### ISSUE THREAD

**Issue by hamcoremusic** [jangxx/OVRT_Soundpad#1]
Hello!

Love this app! I really wish it had a "Stop all sounds" button though... I don't want to have to sit through an entire track sometimes haha

**Comment by jangxx** [comment]
You're in luck, I literally built that feature yesterday (a80a72da83b06789946c7cdca7c74e8fa3a11d52).

The new version is probably going to be live in a few days. If you want to help with development and get the beta version early send me a message on Discord (jangxx#1337).
