### ISSUE TITLE
OVR doesn't see OVRT bridge

### ISSUE THREAD

**Issue by flonicot** [jangxx/OVRT_Soundpad#5]
Accidentally removed the shortcut in OVR and can't find a way to put it back, when i try adding a shortcut i can't find it either and i also tried re-installing ovrt and ovr, nothing changed

**Comment by jangxx** [comment]
I don't think I understand your problem.

>Accidentally removed the shortcut in OVR

The shortcut to what? The custom app or the bridge? Also what do you mean with "OVR"? OVR is short for OpenVR, which is the backbone of most VR apps on steam, but really has no bearing on this.

>when i try adding a shortcut

Again adding a shortcut to where to what?

>tried re-installing ovrt and ovr

Reinstalling OVRT (OVR Toolkit) does nothing. "Reinstalling OVR" would mean reinstalling SteamVR I guess? That also does nothing.

The soundboard app is a workshop item that gets downloaded automatically if you have subscribed to it on the Steam workshop. The only way to "remove" it (afaik) is to unsubscribe from the workshop item. The bridge on the other hand is an independent piece of software that runs alongside everything else and that enables the communication between the soundboard app (running in OVRT) and Soundpad running in the background. You do not run it inside of VR at all; when you run it it puts a small icon into your tray and that's it.

**Comment by flonicot** [comment]
sorry, just kinda mashed words but when i go in vr and i go on the ovr toolkit menu i don't see the bridge app icon to open the soundboard, i accidentally removed the icon and i can`t find a way to put it back

**Comment by flonicot** [comment]
Yeah, done all that but still can't see the icon 😕

**Comment by jangxx** [comment]
So according to the OVR Toolkit developer, removing the shortcut from the phone UI unsubscribes from the workshop item automatically, so you should be able to just go to the workshop again and resubscribe.

**Comment by flonicot** [comment]
alright it's fixed now, thank you very much
