### ISSUE TITLE
Add a way to quickly add all sounds?

### ISSUE THREAD

**Issue by Comic-Tom** [jangxx/OVRT_Soundpad#6]
this was something that has been annoying me. its a pain to add a lot of sounds at ones especially in vr

and not that my config file broke so ive had to reset everything i really wish there was a way to quickly add all my sounds on sound pad to the vr menu

**Comment by jangxx** [comment]
This would definitely be nice to have but how do you imagine this to work? Each sound needs a position on the board, so should I just fill up the board from top-left to bottom-right in alphabetical order and skipping all sounds that don't fit? I can't really think of a good way to automatically place all of these sounds that wouldn't cause more annoyance in the end, especially if you resize the board later.

I'm open to suggestions though, if you have a good idea about how this placement could work I'm all ears and I would happily implement it.

**Comment by Comic-Tom** [comment]
i see it more of a first time set up thing. altho having the option later is also nice if you suddenly gain a lot of sounds. (the action is manually started by the user)
how i would see it working is by starting off filling up the board from top-left to bottom-right. skipping already used spaces. in alphabetical is fine. but excluding sounds that are already added

adding all sounds from sound pad. if it gets the end and cant fit more add a page (or give the user a option to automatically add a pages with a message along the lines of "there are more sounds then available slots did you want to automatically add more pages" yes. no.)

with the resizing of the board later i don't think that's a problem how the add on handles it right now is fine. if the user wants they can clear the board and re add all the sounds or if the user wants if they made the board bigger. and they add more sounds with the "add all" option it starts by filling in the blanks before making a new page

shitty flowchart attached
![image](https://user-images.githubusercontent.com/89974115/191877767-07a5f9d0-fec6-4ad4-b295-8ca3dfa0c9ac.png)

**Comment by jangxx** [comment]
Sounds like a good idea, I'll try adding it once I find the time 👍

**Comment by jangxx** [comment]
Just released a new version 1.2.0, which adds a "Fill Page" system. Let me know if it works for you so we can close this issue.

**Comment by Comic-Tom** [comment]
Been using it, its good. no complaints about it
