### ISSUE TITLE
[Bug?] Doesn't work for free trial (on website)

### ISSUE THREAD

**Issue by Mystery24601** [jangxx/OVRT_Soundpad#9]
This bridge program does not detect Soundpad (or atleast the ovr-toolkit plugin does not) if it was downloaded as a free trial. idk about the demo version of soundpad though, maybe that works, who knows.

**Comment by jangxx** [comment]
That is correct. The trial version does not have the remote control interface that's needed to control it from an external program, so it's impossible to be supported.
